name = "Halide"
uuid = "7a246659-f26e-48cb-9cb1-0d7f4a852a2d"
authors = ["miguel raz <miguelraz@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArtifactUtils = "8b73e784-e7d8-4ea5-973d-377fed4e3bce"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
